(defun %compiled-atom (x quoted?)
  (? (& quoted? x (symbol? x))
     (list 'quote x)
     x))

(defun compiled-list (x &key (quoted? nil))
  (? (cons? x)
     `(cons ,(%compiled-atom x. quoted?)
            ,(compiled-list .x :quoted? quoted?))
	 (%compiled-atom x quoted?)))

(defun compiled-tree (x &key (quoted? nil))
  (? (cons? x)
     `(cons ,(compiled-tree x. :quoted? quoted?)
            ,(compiled-tree .x :quoted? quoted?))
	 (%compiled-atom x quoted?)))
