#!/bin/sh

if [ -f "~/.tre" ]; then \
    while IFS='=' read -r key value; do \
        eval "export \"$key=$value\""; \
    done < ~/.tre; \
fi

sbcl --noinform --control-stack-size 16 \
     --core /usr/local/lib/tre/image $@
