#!/bin/sh

if [ -z "$TRE_PATH" ]; then
  export TRE_PATH=/usr/local/lib/tre;
fi

CONFIG=`eval echo ~/.tre`
if [ -e $CONFIG ]; then
    while IFS='=' read -r key value; do
        export "$key=$value";
    done < $CONFIG;
fi

echo $TRE_PATH
sbcl --noinform --control-stack-size 16 \
     --core $TRE_PATH/image $@
