#!/bin/sh

if [ -z "$TRE_PATH" ]; then
  export TRE_PATH=/usr/local/lib/tre/
fi

SHCONFIG=`eval echo ~/.tre.sh`
if [ -e $SHCONFIG ]; then
echo "config"
    . $SHCONFIG;
fi

echo $TRE_PATH
sbcl --noinform --control-stack-size 16 --core $TRE_PATH/image $@
