(var *universe* nil)
(var *variables* nil)
(var *launchfile* nil)
(var *pointer-size* 4)
(var *assert?* nil)
(var *endianess* nil)
(var *cpu-type* nil)
(var *libc-path* nil)
(var *rand-max* nil)
(var *print-definitions?* nil)
(var *default-stream-tabsize* 8)

(var *quasiquote-expand* nil)
(var *dot-expand* nil)

(var *argv* *posix-argv*)
