(env-load "transpiler/middle-end/accumulate-toplevel-expressions.lisp")
(env-load "transpiler/middle-end/quote-keywords.lisp")
(env-load "transpiler/middle-end/validate-metacode.lisp")
(env-load "transpiler/middle-end/optimizer/main.lisp")
(env-load "transpiler/middle-end/toplevel.lisp")
