(env-load "transpiler/middle-end/accumulate-toplevel-expressions.lisp")
(env-load "transpiler/middle-end/collect-keywords.lisp")
(env-load "transpiler/middle-end/unassign-named-functions.lisp")
(env-load "transpiler/middle-end/validate-metacode.lisp")
(env-load "transpiler/middle-end/optimizer/main.lisp")
(env-load "transpiler/middle-end/delay-statements.lisp")
(env-load "transpiler/middle-end/toplevel.lisp")
