(define-transpiler-end :middleend
    :middleend-input        #'identity
    :expression-expand      #'expression-expand
    :unassign-named-functions       #'unassign-named-functions
    :accumulate-toplevel    #'accumulate-toplevel-expressions
    :quote-keywords         #'quote-keywords
    :validate-metacode      #'validate-metacode
    :optimize               #'optimize
    :opt-tailcall           #'pass-opt-tailcall)
