(env-load "transpiler/targets/javascript/core.lisp")
(env-load "transpiler/targets/javascript/toplevel.lisp")
(env-load "transpiler/targets/javascript/transpiler-macros.lisp")
(env-load "transpiler/targets/javascript/literals.lisp")
(env-load "transpiler/targets/javascript/expression-expand.lisp")
(env-load "transpiler/targets/javascript/codegen.lisp")
(env-load "transpiler/targets/javascript/codegen-inline-cons.lisp")
(env-load "transpiler/targets/javascript/make-js-project.lisp")
