(env-load "transpiler/targets/javascript/argument-filter.lisp")
(env-load "transpiler/targets/javascript/core.lisp")
(env-load "transpiler/targets/javascript/toplevel.lisp")
(env-load "transpiler/targets/javascript/expand.lisp")
(env-load "transpiler/targets/javascript/class.lisp")
(env-load "transpiler/targets/javascript/literals.lisp")
(env-load "transpiler/targets/javascript/codegen.lisp")
(env-load "transpiler/targets/javascript/codegen-inline-cons.lisp")
