;;;;; tré – Copyright (c) 2010,2012–2013 Sven Michael Klose <pixel@copei.de>

(defun cblock-to-metacode (x)
  (with (blks (cdr (butlast x))
         tags (mapcar [cons _ (make-compiler-tag)] blks))
    (mapcan #'((tag cb)
                 (+ (list tag)
                    (cblock-code cb)
                    (!? (cblock-conditional-next cb)
                        `((%%go-nil ,(cblock-conditional-place cb)
                                    ,(assoc-value ! tags :test #'eq)))
                          (awhen (assoc-value (cblock-next cb) tags :test #'eq)
                            `((%%go ,!))))))
            (cdrlist tags)
            blks)))
