;;;;; tré - Copyright (c) 2010 Sven Klose <pixel@copei.de>

(defun print-cblock (cb)
  (format t "--- START ---~%")
  (format t "Ins: ~A" (cblock-ins cb))
  (format t "Merged ins: ~A" (cblock-merged-ins cb))
  (dolist (i (cblock-code cb))
    (princ "    ")
    (late-print i))
  (when (cblock-next cb)
    (format t "Unconditional next.~%"))
  (when (cblock-conditional-next cb)
    (format t "Conditional next.~%"))
  (format t "Outs: ~A~%" (cblock-outs cb))
  (format t "--- END ---~%")
  cb)

(defun print-cblocks (blks)
  (format t "--- CBLOCKS ---~%")
  (map #'print-cblock blks)
  blks)
