; tré – Copyright (c) 2005–2016 Sven Michael Klose <pixel@hugbox.org>

(env-load "transpiler/lib/main.lisp")
(env-load "transpiler/end.lisp")
(env-load "transpiler/back-end/main.lisp")
(env-load "transpiler/middle-end/main.lisp")
(env-load "transpiler/front-end/main.lisp")
(env-load "transpiler/warn-unused-functions.lisp")
(env-load "transpiler/tests.lisp")
(env-load "transpiler/import.lisp")
(env-load "transpiler/compile.lisp")
(env-load "transpiler/targets/main.lisp")
(env-load "transpiler/compile-environment.lisp" :c)
;(env-load "transpiler/eval.lisp" :c)
(env-load "transpiler/make-project.lisp" :c :cl)
