(env-load "transpiler/lib/main.lisp")
(env-load "transpiler/end.lisp")
(env-load "transpiler/back-end/main.lisp")
(env-load "transpiler/middle-end/main.lisp")
(env-load "transpiler/front-end/main.lisp")
(env-load "transpiler/warn-unused-functions.lisp")
(env-load "transpiler/tests.lisp")
(env-load "transpiler/import.lisp")
(env-load "transpiler/compile.lisp")
(env-load "transpiler/targets/main.lisp")
;(env-load "transpiler/eval.lisp")
(env-load "transpiler/make-project.lisp" :cl)
