;;;; TRE transpiler
;;;; Copyright (c) 2005-2009 Sven Klose <pixel@copei.de>

(env-load "transpiler/middle-end/main.lisp")
(env-load "transpiler/config.lisp")

(env-load "transpiler/back-end/escaped-string.lisp")
(env-load "transpiler/back-end/identifier.lisp")
(env-load "transpiler/back-end/finalize.lisp")
(env-load "transpiler/back-end/function-name.lisp")
(env-load "transpiler/back-end/operators.lisp")
(env-load "transpiler/back-end/macros.lisp")
(env-load "transpiler/back-end/string-encapsulation.lisp")
(env-load "transpiler/back-end/obfuscate.lisp")
(env-load "transpiler/back-end/toplevel.lisp")

(env-load "transpiler/front-end/arith-stubs.lisp")
(env-load "transpiler/front-end/newlines.lisp")
(env-load "transpiler/front-end/update-funinfos.lisp")
(env-load "transpiler/front-end/named-functions.lisp")
(env-load "transpiler/front-end/function-arguments.lisp")
(env-load "transpiler/front-end/expression-expand.lisp")
(env-load "transpiler/front-end/expex-funcalls.lisp")
(env-load "transpiler/front-end/expex-funinfo.lisp")
(env-load "transpiler/front-end/expex-global-variables.lisp")
(env-load "transpiler/front-end/prepare-runtime-argexps.lisp")
(env-load "transpiler/front-end/lambda-expand.lisp")
(env-load "transpiler/front-end/literals.lisp")
(env-load "transpiler/front-end/quote-keywords.lisp")
(env-load "transpiler/front-end/macros.lisp")
(env-load "transpiler/front-end/standard-macros.lisp")
(env-load "transpiler/front-end/import.lisp")
(env-load "transpiler/front-end/toplevel.lisp")

(env-load "transpiler/toplevel.lisp")

(env-load "transpiler/targets/c/expex-literals.lisp")
(env-load "transpiler/targets/c/config.lisp")
(env-load "transpiler/targets/c/expand.lisp")
(env-load "transpiler/targets/c/builtin.lisp")
(env-load "transpiler/targets/c/codegen.lisp")
(env-load "transpiler/targets/c/toplevel.lisp")

(env-load "transpiler/targets/javascript/config.lisp")
(env-load "transpiler/targets/javascript/expand.lisp")
(env-load "transpiler/targets/javascript/codegen.lisp")
(env-load "transpiler/targets/javascript/codegen-inline.lisp")
(env-load "transpiler/targets/javascript/env-load.lisp")
(env-load "transpiler/targets/javascript/tests.lisp")
(env-load "transpiler/targets/javascript/toplevel.lisp")

(env-load "transpiler/targets/php/expex.lisp")
(env-load "transpiler/targets/php/expex-literals.lisp")
(env-load "transpiler/targets/php/config.lisp")
(env-load "transpiler/targets/php/expand.lisp")
(env-load "transpiler/targets/php/codegen.lisp")
(env-load "transpiler/targets/php/codegen-inline.lisp")
(env-load "transpiler/targets/php/core.lisp")
(env-load "transpiler/targets/php/toplevel.lisp")
