(fn eq (a b)
  (& (is_a a "__symbol")
     (%%%== a.n "T")
     (= a t))
  (& (is_a b "__symbol")
     (%%%== b.n "T")
     (= b t))
  (| (%%%=== a b)
     (& (is_a a "__cons")
        (is_a b "__cons")
        (%%%== a.id b.id))
     (& (is_a a "__symbol")
        (is_a b "__symbol")
        (%%%== a.n b.n)
        (%%%== (keyword? a) (keyword? b)))))
