(env-load "stage0/main.lisp")
(env-load "stage1/main.lisp")
(env-load "stage2/main.lisp")
(env-load "stage3/main.lisp")
(env-load "stage4/main.lisp")
(env-load "stage5/main.lisp")
(env-load "math/main.lisp")
(env-load "oo/class.lisp")
(env-load "utils/git-revision.lisp")
(env-load "transpiler/main.lisp")
(env-load "read-eval-loop.lisp")
(env-load "utils/lml-utils.lisp")
(env-load "utils/lml2xml.lisp")
(env-load "utils/print-html-script.lisp")
(env-load "tests/main.lisp")
(env-load "todo.lisp" :cl)
(env-load "config-after-reload.lisp" :cl)
(env-load "make-vim-syntax-file.lisp" :cl)
(env-load "utils/write-image.lisp" :cl)
