;;; tré – Copyright (c) 2013 Sven Michael Klose <pixel@copei.de>

#include "config.asm"
#include "basic-loader.asm"
#include "main.asm"
#include "exit.asm"
#include "banking.asm"
#include "console.asm"
#include "vstack.asm"
#include "cons.asm"
#include "atom.asm"
#include "gc.asm"
#include "messages.asm"
#include "cons-init.asm"
#include "atom-init.asm"
