(fn atan2 (x y)
  (with (c1  (/ *pi* 4)
         c2  (* 3 c1)
         ay  (abs y))
    (let angle (? (>= x 0)
                  (!= (/ (- x ay) (+ x ay))
                    (- c1 (* c1 !)))
                  (!= (/ (+ x ay) (- ay x))
                    (- c2 (* c1 !))))
      (? (< y 0)
         (- angle)
         angle))))
