;;;;; tré – Copyright (c) 2006–2009,2012–2014 Sven Michael Klose <pixel@copei.de>

(%defvar *show-definitions?* t)
(%defvar *defined-functions* nil)
(%defvar *universe* nil)
(%defvar *keyword-package* nil)
(%defvar *show-definitions?* nil)
(%defvar *environment-path* nil)
(%defvar *endianess* nil)
(%defvar *pointer-size* nil)
(%defvar *cpu-type* nil)
(%defvar *libc-path* nil)
(%defvar *have-environment-tests* nil)
(%defvar *rand-max* nil)
(%defvar *default-listprop* nil)
(%defvar *exception* nil)
(%defvar *backtrace* nil)
(%defvar *assert* nil)
(%defvar *targets* nil)
(%defvar *development?* t)

(%defun identity (x) x)
