(env-load "stage2/multiple-value-bind.lisp")
(env-load "stage2/values.lisp")
(env-load "stage2/while.lisp")
(env-load "stage2/with.lisp")
(env-load "stage2/array.lisp")
(env-load "stage2/xchg.lisp")
(env-load "stage2/group.lisp")
(env-load "stage2/pcase.lisp")
(env-load "stage2/remove.lisp")
(env-load "stage2/subseq-c.lisp" :cl)
(env-load "stage2/subseq.lisp")
(env-load "stage2/subseq-tests.lisp")
(env-load "stage2/range.lisp")
(env-load "stage2/char.lisp")
(env-load "stage2/char-predicates.lisp")
(env-load "stage2/string.lisp")
(env-load "stage2/string-c.lisp" :cl)
(env-load "stage2/search-sequence.lisp")
(env-load "stage2/list-symbol.lisp")
(env-load "stage2/dot-expand.lisp")
(env-load "stage2/define-mapped-fun.lisp")
(env-load "stage2/assoc.lisp")
(env-load "stage2/assoc-value.lisp")
(env-load "stage2/pairlist.lisp")
(env-load "stage2/in.lisp")
(env-load "stage2/defstruct.lisp")
(env-load "stage2/abs.lisp" :cl)
(env-load "stage2/doarray.lisp")
(env-load "stage2/dosequence.lisp")
(env-load "stage2/list-array.lisp" :cl)
(env-load "stage2/aadjoin.lisp")
