(functional string<=)
(fn string<= (a b)
  (with (la  (length a)
         lb  (length b))
    (dotimes (i la (<= la lb))
      (& (character> (elt a i) (elt b i))
         (return nil)))))

(functional string-list)
(fn string-list (x)
  (with (l  (length x)
         s  nil)
    (do ((i (-- l) (-- i)))
        ((< i 0))
      (= s (push (elt x i) s)))
    s))

(functional queue-string)
(fn queue-string (x)
  (list-string (queue-list x)))
