;;;;; tré - Copyright (c) 2011 Sven Michael Klose <pixel@copei.de>

(defun make-levenshtein (row column)
  (with (width (length row)
         height (length column)
         w (integer-1+ width)
         h (integer-1+ height)
         m (make-array)); w h))
    (dotimes (i w)
      (setf (aref m i) (make-array)))
    (dotimes (i w)
      (dotimes (j h)
        (setf (aref m i j ) 0)))
    (dotimes (i w)
      (setf (aref m i 0) i))
    (dotimes (j h)
      (setf (aref m 0 j ) j))
    (dotimes (jc height) 
      (dotimes (ic width) 
        (with (i (integer-1+ ic)
               j (integer-1+ jc))
          (setf (aref m i j)
                (min (integer+ (aref m ic jc)
                        (? (= (elt row ic) (elt column jc))
                           0
                           1))
                     (integer+ (aref m ic j) 1)
                     (integer+ (aref m i jc) 1))))))
    m))

(defun levenshtein (row column)
  (aref (make-levenshtein row column) (length row) (length column)))
