;;;; tré – Copyright (c) 2010-2012 Sven Michael Klose <pixel@copei.de>

(env-load "stage5/in-package.lisp" 'c)
(env-load "stage5/alist-assignments.lisp")
(env-load "stage5/array-list.lisp")
(env-load "stage5/backslash-to-slash.lisp")
(env-load "stage5/base64.lisp" 'c)
(env-load "stage5/camelize.lisp")
(env-load "stage5/comma-separated-list.lisp")
(env-load "stage5/doseq.lisp")
(env-load "stage5/english-numbers.lisp")
(env-load "stage5/half.lisp")
(env-load "stage5/kwlist.lisp")
(env-load "stage5/levenshtein.lisp")
(env-load "stage5/make-upcase-symbol.lisp")
(env-load "stage5/make-keywords.lisp")
(env-load "stage5/make-symbols.lisp")
(env-load "stage5/merge-unique.lisp")
(env-load "stage5/pad-string-concat.lisp")
(env-load "stage5/string-char.lisp" 'c)
(env-load "stage5/string-has-whitespace-p.lisp")
(env-load "stage5/stringlist-skip-spaces.lisp")
(env-load "stage5/symbol-names.lisp")
(env-load "stage5/symbol-without-package.lisp")
(env-load "stage5/toggle.lisp")
(env-load "stage5/trim-double-spaces.lisp")
(env-load "stage5/trim-crlf.lisp")
(env-load "stage5/trim-spaces.lisp")
(env-load "stage5/without-head.lisp")
(env-load "stage5/without-tail.lisp")
(env-load "stage5/read-binary-file.lisp")
(env-load "stage5/read-bmp-array.lisp")
(env-load "stage5/parenthized-comma-separated-list.lisp")
(env-load "stage5/percent.lisp")
(env-load "stage5/bmp2cub.lisp")
(env-load "stage5/ppm.lisp")
