(env-load "stage5/base64.lisp")
(env-load "stage5/byte.lisp")
;(env-load "stage5/in-package.lisp" :c)
(env-load "stage5/flatten.lisp")
(env-load "stage5/escape-string.lisp")
(env-load "stage5/empty-string.lisp")
(env-load "stage5/iterate.lisp")
(env-load "stage5/list+.lisp")
(env-load "stage5/make-keyword.lisp")
(env-load "stage5/quoted.lisp")
(env-load "stage5/toggle.lisp")
(env-load "stage5/permutate.lisp")

(env-load "stage5/email-domain.lisp")
(env-load "stage5/path.lisp")
(env-load "stage5/data-url.lisp")
(env-load "stage5/url-path.lisp")
