(const *pi* *math.*p-i)

(fn abs (x)     (*math.abs x))
(fn acos (x)    (*math.acos x))
(fn asin (x)    (*math.asin x))
(fn atan (x)    (*math.atan x))
(fn atan2 (a b) (*math.atan2 a b))
(fn ceil (x)    (*math.ceil x))
(fn cos (x)     (*math.cos x))
(fn exp (x)     (*math.exp x))
(fn floor (x)   (*math.floor x))
(fn log (x)     (*math.log x))
(fn max (a b)   (*math.max a b))
(fn min (a b)   (*math.min a b))
(fn pow (x y)   (*math.pow x y))
(fn round (x)   (*math.round x))
(fn sin (x)     (*math.sin x))
(fn sqrt (x)    (*math.sqrt x))
(fn tan (x)     (*math.tan x))
(fn random ()   (*math.random))
