;;;;; tré – Copyright (c) 2005–2010,2012–2013 Sven Michael Klose <pixel@copei.de>

(env-load "transpiler/back-end/identifier-style-convert.lisp")
(env-load "transpiler/back-end/macros.lisp")
(env-load "transpiler/back-end/operators.lisp")
(env-load "transpiler/back-end/count-tags.lisp")
(env-load "transpiler/back-end/wrap-tags.lisp")
(env-load "transpiler/back-end/string-encapsulation.lisp")
(env-load "transpiler/back-end/obfuscate.lisp")
(env-load "transpiler/back-end/translate-function-names.lisp")
(env-load "transpiler/back-end/function-name.lisp")
(env-load "transpiler/back-end/warn-unused.lisp")
(env-load "transpiler/back-end/place-expand.lisp")
(env-load "transpiler/back-end/place-assign.lisp")
(env-load "transpiler/back-end/copy-arguments-to-vars.lisp")
(env-load "transpiler/back-end/make-framed-functions.lisp")
(env-load "transpiler/back-end/closure.lisp")
(env-load "transpiler/back-end/toplevel.lisp")
