(defun documentation (sym)
  (!? (assoc-value sym *documentation*)
	  (format t "Documentation for ~A:~%~A~%" sym !))
  (awhen (symbol-function sym)
	(format t "Arguments to ~A:~%~A~%" sym (function-arguments !))))
