(env-load "stage3/object.lisp" :cl)
(env-load "stage3/ref.lisp")
(env-load "stage3/let-when.lisp")
(env-load "stage3/ensure-tree.lisp")
(env-load "stage3/declare.lisp")
(env-load "stage3/maphash.lisp")
(env-load "stage3/alist-hash.lisp")
(env-load "stage3/with-struct.lisp")
(env-load "stage3/stream.lisp" :cl)
(env-load "stage3/standard-stream.lisp" :cl)
(env-load "stage3/default-stream.lisp")
(env-load "stage3/stream-stream.lisp")
(env-load "stage3/open.lisp")
(env-load "stage3/with-file.lisp")
(env-load "stage3/string-stream.lisp")
(env-load "stage3/with-string-stream.lisp")
(env-load "stage3/copying-stream.lisp")
(env-load "stage3/with-temporary.lisp")
(env-load "stage3/force-output.lisp" :cl)
(env-load "stage3/princ-number.lisp" :cl)
(env-load "stage3/princ.lisp")
(env-load "stage3/line.lisp")
(env-load "stage3/def-head-predicate.lisp")
(env-load "stage3/argument-expand.lisp")
(env-load "stage3/stream-predicates.lisp")
;(env-load "stage3/print-tracer.lisp")
(env-load "stage3/terpri.lisp")
(env-load "stage3/print-c.lisp" :cl)
(env-load "stage3/print.lisp")
(env-load "stage3/print-number.lisp")
(env-load "stage3/cache.lisp")
(env-load "stage3/loop.lisp")
(env-load "stage3/read-char.lisp")
(env-load "stage3/read-hex.lisp")
(env-load "stage3/read-number.lisp")
(env-load "stage3/read-line.lisp")
(env-load "stage3/read.lisp")
(env-load "stage3/read-file.lisp")
(env-load "stage3/read-byte.lisp")
(env-load "stage3/read-chars.lisp")
(env-load "stage3/read-binary.lisp")
(env-load "stage3/file.lisp")
(env-load "stage3/format.lisp")
(env-load "stage3/dump.lisp" :cl)
(env-load "stage3/error.lisp" :cl)
(env-load "stage3/type.lisp")
(env-load "stage3/bit-stream.lisp")
(env-load "stage3/documentation.lisp")
(env-load "stage3/assert.lisp")
(env-load "stage3/assert-c.lisp" :cl)
(env-load "stage3/collected-errors.lisp")
(env-load "stage3/string-integer.lisp" :cl)
(env-load "stage3/directory.lisp" :cl)
