;;;; tré – Copyright (C) 2005–2009,2011–2014 Sven Michael Klose <pixel@copei.de>

(env-load "stage3/list-unless.lisp")
(env-load "stage3/ensure-tree.lisp")
(env-load "stage3/declare.lisp")
(env-load "stage3/hash.lisp" 'c)
(env-load "stage3/profile.lisp")
(env-load "stage3/with-struct.lisp")
(env-load "stage3/stream.lisp" 'c)
(env-load "stage3/standard-stream.lisp" 'c)
(env-load "stage3/default-stream.lisp")
(env-load "stage3/open.lisp")
(env-load "stage3/with-file.lisp")
(env-load "stage3/string-stream.lisp")
(env-load "stage3/with-string-stream.lisp")
(env-load "stage3/with-temporary.lisp")
(env-load "stage3/object-p.lisp" 'c)
(env-load "stage3/princ.lisp")
(env-load "stage3/line.lisp")
(env-load "stage3/force-output.lisp" 'c)
(env-load "stage3/argument-expand.lisp")
;(env-load "stage3/print-tracer.lisp")
(env-load "stage3/print-c.lisp" 'c)
(env-load "stage3/print.lisp")
(env-load "stage3/print-number.lisp")
(env-load "stage3/stream-predicates.lisp")
(env-load "stage3/cache.lisp")
(env-load "stage3/memorized-number.lisp")
(env-load "stage3/loop.lisp")
(env-load "stage3/read-char.lisp")
(env-load "stage3/read-hex.lisp" 'c)
(env-load "stage3/read-number.lisp")
(env-load "stage3/read-line.lisp")
(env-load "stage3/read.lisp")
(env-load "stage3/read-file.lisp")
(env-load "stage3/file.lisp")
(env-load "stage3/format.lisp")
(env-load "stage3/terpri.lisp")
(env-load "stage3/error.lisp" 'c)
(env-load "stage3/documentation.lisp")
(env-load "stage3/assert.lisp")
(env-load "stage3/assert-c.lisp" 'c)
(env-load "stage3/collected-errors.lisp")
(env-load "stage3/string-integer.lisp" 'c)
