(defmacro @ (what &body body)
  (alet (macroexpand what)
    (?
      (cons? !)
        (? (eq 'function (car !))
           `(mapcar ,! ,@body)
           `(dolist ,! ,@body))
      (symbol? what)
        `(mapcar ,! ,@body)
      (error !))))
