(env-load "stage1/gensym.lisp")
(env-load "stage1/documentation.lisp")
(env-load "stage1/defmacro.lisp" :cl)
(env-load "stage1/deftest.lisp" :cl)
(env-load "stage1/return.lisp")
(env-load "stage1/andor.lisp")
(env-load "stage1/brackets.lisp")
(env-load "stage1/defun.lisp" :cl)
(env-load "stage1/predicates.lisp")
(env-load "stage1/arg-keyword-p.lisp")
(env-load "stage1/prog1.lisp")
(env-load "stage1/let.lisp")
(env-load "stage1/queue.lisp")
(env-load "stage1/mapcar.lisp")
(env-load "stage1/do.lisp")
(env-load "stage1/dolist.lisp")
(env-load "stage1/anaphoric.lisp")
(env-load "stage1/member.lisp")
(env-load "stage1/slot-value-p.lisp")
(env-load "stage1/fboundp.lisp")
(env-load "stage1/setf-function-p.lisp" :cl)
(env-load "stage1/=.lisp")
(env-load "stage1/math.lisp")
(env-load "stage1/abs.lisp" :cl)
(env-load "stage1/list.lisp")
(env-load "stage1/set.lisp")
(env-load "stage1/cons-r.lisp")
(env-load "stage1/count.lisp")
(env-load "stage1/integerp.lisp" :cl)
(env-load "stage1/conditional.lisp")
(env-load "stage1/@.lisp")
(env-load "stage1/dotimes.lisp")
(env-load "stage1/lambda.lisp")
(env-load "stage1/function-source.lisp" :cl)
(env-load "stage1/dollar.lisp")
(env-load "stage1/with-queue.lisp")
(env-load "stage1/maptimes.lisp")
(env-load "stage1/with-cons.lisp")
(env-load "stage1/with-gensym.lisp")
(env-load "stage1/define-filter.lisp")
(env-load "stage1/char.lisp")
