version: "3.9"

services:
  app:
    container_name: tre_examples_project_js
    build:
      context: ./docker/httpd
    network_mode: bridge
    ports:
      - "19020:80"
    volumes:
      - appdata:/var/www/html:rw

volumes:
  appdata:
    name: tre_examples_project_js_appdata
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./
