;;;;; tré – Copyright (c) 2008–2013 Sven Michael Klose <pixel@copei.de>

(define-optimizer optimize-places
  (& (%setq? a)
     (%setq? d.)
     (eq (%setq-place a) (%setq-value d.))
     (not (opt-peephole-will-be-used-again? .d (%setq-place a))))
    (. `(%setq ,(%setq-place d.) ,(%setq-value a))
       (optimize-places .d))
  (& (%setq? a)
     (%setq? d.)
     (atom (%setq-value a))
     (cons? (%setq-value d.))
     (find-tree (%setq-place a) (%setq-value d.) :test #'eq)
     (not (opt-peephole-will-be-used-again? .d (%setq-place a))))
    (.  (replace-tree (%setq-place a) (%setq-value a)
                      `(%setq ,(%setq-place d.) ,(%setq-value d.))
                      :test #'eq)
       (optimize-places .d))
  (& (%setq? a)
     (not (opt-peephole-will-be-used-again? d (%setq-place a))))
    (. `(%setq nil ,(%setq-value a))
       (optimize-places d)))
