version: "3.9"

services:
  app:
    build:
      context: ./docker/httpd
    links:
      - db
    network_mode: bridge
    ports:
      - "19020:80"
    volumes:
      - appdata:/var/www/html:rw

  db:
    image: mysql:latest
    network_mode: bridge
    environment:
      MYSQL_DATABASE: fnord
      MYSQL_USER: fnord
      MYSQL_PASSWORD: fnord
      MYSQL_ROOT_PASSWORD: fnord
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql:rw

volumes:
  appdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./
  dbdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/mysql
