; tré – Copyright (c) 2010–2015 Sven Michael Klose <pixel@copei.de>

(env-load "transpiler/targets/shared/builtin.lisp")
(env-load "transpiler/targets/shared/core-variables.lisp")
(env-load "transpiler/targets/shared/functionals.lisp")
(env-load "transpiler/targets/shared/noargs-tag.lisp")
(env-load "transpiler/targets/shared/expand/defun.lisp")
(env-load "transpiler/targets/shared/expand/class.lisp")
(env-load "transpiler/targets/shared/expand/opt-string-concat.lisp")
(env-load "transpiler/targets/shared/codegen/newline.lisp")
(env-load "transpiler/targets/shared/codegen/literal-string.lisp")
(env-load "transpiler/targets/shared/codegen/c-list.lisp")
(env-load "transpiler/targets/shared/codegen/alist-assignments.lisp")
(env-load "transpiler/targets/shared/codegen/define-macro-definer.lisp")
(env-load "transpiler/targets/shared/codegen/funinfo-comment.lisp")
