;;;;; tré – Copyright (c) 2010–2012 Sven Michael Klose <pixel@copei.de>

(env-load "transpiler/targets/shared/builtin.lisp")
(env-load "transpiler/targets/shared/noargs-tag.lisp")
(env-load "transpiler/targets/shared/expand/log-function-calls.lisp")
(env-load "transpiler/targets/shared/expand/defun.lisp")
(env-load "transpiler/targets/shared/expand/defmacro.lisp")
(env-load "transpiler/targets/shared/expand/defvar.lisp")
(env-load "transpiler/targets/shared/expand/mapcar.lisp")
(env-load "transpiler/targets/shared/expand/not.lisp")
(env-load "transpiler/targets/shared/expand/opt-string-concat.lisp")
(env-load "transpiler/targets/shared/expand/opt-filter.lisp")
(env-load "transpiler/targets/shared/expand/setf-cons.lisp")
(env-load "transpiler/targets/shared/codegen/define-macro-definer.lisp")
(env-load "transpiler/targets/shared/codegen/codegen-expr-p.lisp")
(env-load "transpiler/targets/shared/codegen/compiled-symbol-identifier.lisp")
