(fn make-object (&rest x)
  (!= (%%%make-object)
    (@ (i (group x 2) !)
      (= (slot-value ! (? (symbol? i.)
                          (downcase (symbol-name i.))
                          i.))
         .i.))))
