;;;; TRE transpiler
;;;; Copyright (c) 2005-2010 Sven Klose <pixel@copei.de>

(env-load "transpiler/front-end/expression-expand.lisp")
(env-load "transpiler/front-end/expex-funcalls.lisp")
(env-load "transpiler/front-end/expex-funinfo.lisp")
(env-load "transpiler/front-end/expex-global-variables.lisp")
(env-load "transpiler/front-end/opt-inline.lisp")
(env-load "transpiler/front-end/rename-args.lisp")
(env-load "transpiler/front-end/rename-tags.lisp")
(env-load "transpiler/front-end/compiler-macros.lisp")
(env-load "transpiler/front-end/arith-stubs.lisp")
(env-load "transpiler/front-end/newlines.lisp")
(env-load "transpiler/front-end/function-arguments.lisp")
(env-load "transpiler/front-end/backquote-expand.lisp")
(env-load "transpiler/front-end/lambda-expand.lisp")
(env-load "transpiler/front-end/literals.lisp")
(env-load "transpiler/front-end/quote-keywords.lisp")
(env-load "transpiler/front-end/macros.lisp")
(env-load "transpiler/front-end/splice.lisp")
(env-load "transpiler/front-end/standard-macros.lisp")
(env-load "transpiler/front-end/import.lisp")
(env-load "transpiler/front-end/toplevel.lisp")
