;;;; TRE transpiler
;;;; Copyright (c) 2005-2009 Sven Klose <pixel@copei.de>

(env-load "../transpiler/utils.lisp")
(env-load "../transpiler/config.lisp")
(env-load "../transpiler/identifier.lisp")
(env-load "../transpiler/named-functions.lisp")
(env-load "../transpiler/expand.lisp")
(env-load "../transpiler/codegen.lisp")
(env-load "../transpiler/obfuscate.lisp")
(env-load "../transpiler/import.lisp")
(env-load "../transpiler/toplevel.lisp")
(env-load "../transpiler/javascript/config.lisp")
(env-load "../transpiler/javascript/expand.lisp")
(env-load "../transpiler/javascript/codegen.lisp")
(env-load "../transpiler/javascript/core.lisp")
(env-load "../transpiler/javascript/toplevel.lisp")
;(env-load "../transpiler/c/config.lisp")
;(env-load "../transpiler/c/expand.lisp")
;(env-load "../transpiler/c/codegen.lisp")
;(env-load "../transpiler/c/core.lisp")
;(env-load "../transpiler/c/toplevel.lisp")
