;(define-php-binary - "-")
(define-php-binary / "/")
(define-php-binary * "*")
;(define-php-binary == "==") ; XXX these will give us trouble with chars.
;(define-php-binary < "<")
;(define-php-binary > ">")
(define-php-binary string== "==")
(define-php-binary >> ">>")
(define-php-binary << "<<")
(define-php-binary mod "%")
(define-php-binary tre_eq "===")
(define-php-binary bit-and "&")
(define-php-binary bit-or "|")
(define-php-binary bit-xor "^")

(def-php-codegen identity (x)
  x)

(def-php-codegen tre_cons (x y)
  `("new " ,(convert-identifier '__cons) " (" ,(php-dollarize x) ", " ,(php-dollarize y) ")"))
