(env-load "transpiler/targets/php/core.lisp")
(env-load "transpiler/targets/php/literals.lisp")
(env-load "transpiler/targets/php/toplevel.lisp")
(env-load "transpiler/targets/php/transpiler-macros.lisp")
(env-load "transpiler/targets/php/expression-expand.lisp")
(env-load "transpiler/targets/php/codegen.lisp")
;(env-load "transpiler/targets/php/codegen-inline.lisp")
(env-load "transpiler/targets/php/make-php-project.lisp")
