name: Build and test on Ubuntu

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

    - name: Update repos
      run: sudo apt-get update -y

    - name: Set up prerequisites
      run: sudo apt-get install -y sbcl

    - name: Set up Quicklisp
      run: |
        curl -O https://beta.quicklisp.org/quicklisp.lisp
        sbcl --load quicklisp.lisp --eval '(quicklisp-quickstart:install)' --eval '(quicklisp:add-to-init-file)' --quit

    - name: Load UIOP and run tests
      run: |
        sbcl --eval '(ql:quickload :uiop)' --quit

    - name: Set up Github environment
      id: setup_environment
      run: |
        SHORT_SHA=$(git rev-parse --short HEAD)
        DATE=`date +"%Y-%m-%d"`
        echo "TRE_DEVELOPMENT=1" >> $GITHUB_ENV
        echo "TRE_DEBUG=1" >> $GITHUB_ENV

    - name: Build
      run: ./make.sh boot

    - name: Install
      run: sudo ./make.sh install
